// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: stats.service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatisticsService_GetStream_FullMethodName           = "/api.StatisticsService/GetStream"
	StatisticsService_GetTraces_FullMethodName           = "/api.StatisticsService/GetTraces"
	StatisticsService_QueryMetric_FullMethodName         = "/api.StatisticsService/QueryMetric"
	StatisticsService_GetProjectSummary_FullMethodName   = "/api.StatisticsService/GetProjectSummary"
	StatisticsService_GetAvailableFlows_FullMethodName   = "/api.StatisticsService/GetAvailableFlows"
	StatisticsService_GetAvailableMetrics_FullMethodName = "/api.StatisticsService/GetAvailableMetrics"
	StatisticsService_GetTraceByID_FullMethodName        = "/api.StatisticsService/GetTraceByID"
)

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	GetStream(ctx context.Context, in *StatisticsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatisticsStreamResponse], error)
	GetTraces(ctx context.Context, in *StatisticsGetTracesRequest, opts ...grpc.CallOption) (*StatisticsGetTracesResponse, error)
	QueryMetric(ctx context.Context, in *QueryMetricRequest, opts ...grpc.CallOption) (*QueryMetricResponse, error)
	// GetProjectSummary returns aggregated summary of all metrics for a project
	GetProjectSummary(ctx context.Context, in *GetProjectSummaryRequest, opts ...grpc.CallOption) (*GetProjectSummaryResponse, error)
	// GetAvailableFlows returns list of flows for a project
	GetAvailableFlows(ctx context.Context, in *GetAvailableFlowsRequest, opts ...grpc.CallOption) (*GetAvailableFlowsResponse, error)
	// GetAvailableMetrics returns list of available metrics for a project/flow
	GetAvailableMetrics(ctx context.Context, in *GetAvailableMetricsRequest, opts ...grpc.CallOption) (*GetAvailableMetricsResponse, error)
	// GetTraceByID returns complete trace information including all spans by trace ID
	GetTraceByID(ctx context.Context, in *GetTraceByIDRequest, opts ...grpc.CallOption) (*GetTraceByIDResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetStream(ctx context.Context, in *StatisticsStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatisticsStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StatisticsService_ServiceDesc.Streams[0], StatisticsService_GetStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatisticsStreamRequest, StatisticsStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StatisticsService_GetStreamClient = grpc.ServerStreamingClient[StatisticsStreamResponse]

func (c *statisticsServiceClient) GetTraces(ctx context.Context, in *StatisticsGetTracesRequest, opts ...grpc.CallOption) (*StatisticsGetTracesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticsGetTracesResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTraces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) QueryMetric(ctx context.Context, in *QueryMetricRequest, opts ...grpc.CallOption) (*QueryMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMetricResponse)
	err := c.cc.Invoke(ctx, StatisticsService_QueryMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetProjectSummary(ctx context.Context, in *GetProjectSummaryRequest, opts ...grpc.CallOption) (*GetProjectSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectSummaryResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetProjectSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetAvailableFlows(ctx context.Context, in *GetAvailableFlowsRequest, opts ...grpc.CallOption) (*GetAvailableFlowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableFlowsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetAvailableFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetAvailableMetrics(ctx context.Context, in *GetAvailableMetricsRequest, opts ...grpc.CallOption) (*GetAvailableMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableMetricsResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetAvailableMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetTraceByID(ctx context.Context, in *GetTraceByIDRequest, opts ...grpc.CallOption) (*GetTraceByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTraceByIDResponse)
	err := c.cc.Invoke(ctx, StatisticsService_GetTraceByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility.
type StatisticsServiceServer interface {
	GetStream(*StatisticsStreamRequest, grpc.ServerStreamingServer[StatisticsStreamResponse]) error
	GetTraces(context.Context, *StatisticsGetTracesRequest) (*StatisticsGetTracesResponse, error)
	QueryMetric(context.Context, *QueryMetricRequest) (*QueryMetricResponse, error)
	// GetProjectSummary returns aggregated summary of all metrics for a project
	GetProjectSummary(context.Context, *GetProjectSummaryRequest) (*GetProjectSummaryResponse, error)
	// GetAvailableFlows returns list of flows for a project
	GetAvailableFlows(context.Context, *GetAvailableFlowsRequest) (*GetAvailableFlowsResponse, error)
	// GetAvailableMetrics returns list of available metrics for a project/flow
	GetAvailableMetrics(context.Context, *GetAvailableMetricsRequest) (*GetAvailableMetricsResponse, error)
	// GetTraceByID returns complete trace information including all spans by trace ID
	GetTraceByID(context.Context, *GetTraceByIDRequest) (*GetTraceByIDResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticsServiceServer struct{}

func (UnimplementedStatisticsServiceServer) GetStream(*StatisticsStreamRequest, grpc.ServerStreamingServer[StatisticsStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTraces(context.Context, *StatisticsGetTracesRequest) (*StatisticsGetTracesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraces not implemented")
}
func (UnimplementedStatisticsServiceServer) QueryMetric(context.Context, *QueryMetricRequest) (*QueryMetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMetric not implemented")
}
func (UnimplementedStatisticsServiceServer) GetProjectSummary(context.Context, *GetProjectSummaryRequest) (*GetProjectSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjectSummary not implemented")
}
func (UnimplementedStatisticsServiceServer) GetAvailableFlows(context.Context, *GetAvailableFlowsRequest) (*GetAvailableFlowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableFlows not implemented")
}
func (UnimplementedStatisticsServiceServer) GetAvailableMetrics(context.Context, *GetAvailableMetricsRequest) (*GetAvailableMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableMetrics not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTraceByID(context.Context, *GetTraceByIDRequest) (*GetTraceByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraceByID not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}
func (UnimplementedStatisticsServiceServer) testEmbeddedByValue()                           {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	// If the following call panics, it indicates UnimplementedStatisticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatisticsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatisticsServiceServer).GetStream(m, &grpc.GenericServerStream[StatisticsStreamRequest, StatisticsStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StatisticsService_GetStreamServer = grpc.ServerStreamingServer[StatisticsStreamResponse]

func _StatisticsService_GetTraces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsGetTracesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTraces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTraces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTraces(ctx, req.(*StatisticsGetTracesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_QueryMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).QueryMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_QueryMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).QueryMetric(ctx, req.(*QueryMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetProjectSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetProjectSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetProjectSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetProjectSummary(ctx, req.(*GetProjectSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetAvailableFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetAvailableFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetAvailableFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetAvailableFlows(ctx, req.(*GetAvailableFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetAvailableMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetAvailableMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetAvailableMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetAvailableMetrics(ctx, req.(*GetAvailableMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetTraceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTraceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatisticsService_GetTraceByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTraceByID(ctx, req.(*GetTraceByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTraces",
			Handler:    _StatisticsService_GetTraces_Handler,
		},
		{
			MethodName: "QueryMetric",
			Handler:    _StatisticsService_QueryMetric_Handler,
		},
		{
			MethodName: "GetProjectSummary",
			Handler:    _StatisticsService_GetProjectSummary_Handler,
		},
		{
			MethodName: "GetAvailableFlows",
			Handler:    _StatisticsService_GetAvailableFlows_Handler,
		},
		{
			MethodName: "GetAvailableMetrics",
			Handler:    _StatisticsService_GetAvailableMetrics_Handler,
		},
		{
			MethodName: "GetTraceByID",
			Handler:    _StatisticsService_GetTraceByID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _StatisticsService_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stats.service.proto",
}
