// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.29.3
// source: statistics.messages.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticsStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowID    string `protobuf:"bytes,1,opt,name=FlowID,proto3" json:"FlowID,omitempty"`
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
}

func (x *StatisticsStreamRequest) Reset() {
	*x = StatisticsStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsStreamRequest) ProtoMessage() {}

func (x *StatisticsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsStreamRequest.ProtoReflect.Descriptor instead.
func (*StatisticsStreamRequest) Descriptor() ([]byte, []int) {
	return file_statistics_messages_proto_rawDescGZIP(), []int{0}
}

func (x *StatisticsStreamRequest) GetFlowID() string {
	if x != nil {
		return x.FlowID
	}
	return ""
}

func (x *StatisticsStreamRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

type StatisticsStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*StatsEvent `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
}

func (x *StatisticsStreamResponse) Reset() {
	*x = StatisticsStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsStreamResponse) ProtoMessage() {}

func (x *StatisticsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsStreamResponse.ProtoReflect.Descriptor instead.
func (*StatisticsStreamResponse) Descriptor() ([]byte, []int) {
	return file_statistics_messages_proto_rawDescGZIP(), []int{1}
}

func (x *StatisticsStreamResponse) GetEvents() []*StatsEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type StatisticsGetTracesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlowID string `protobuf:"bytes,1,opt,name=FlowID,proto3" json:"FlowID,omitempty"`
	Start  int64  `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End    int64  `protobuf:"varint,3,opt,name=End,proto3" json:"End,omitempty"`
	Offset int64  `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *StatisticsGetTracesRequest) Reset() {
	*x = StatisticsGetTracesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsGetTracesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsGetTracesRequest) ProtoMessage() {}

func (x *StatisticsGetTracesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsGetTracesRequest.ProtoReflect.Descriptor instead.
func (*StatisticsGetTracesRequest) Descriptor() ([]byte, []int) {
	return file_statistics_messages_proto_rawDescGZIP(), []int{2}
}

func (x *StatisticsGetTracesRequest) GetFlowID() string {
	if x != nil {
		return x.FlowID
	}
	return ""
}

func (x *StatisticsGetTracesRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *StatisticsGetTracesRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *StatisticsGetTracesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type StatisticsGetTracesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Traces []*Trace `protobuf:"bytes,1,rep,name=Traces,proto3" json:"Traces,omitempty"`
	Total  int64    `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	Offset int64    `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *StatisticsGetTracesResponse) Reset() {
	*x = StatisticsGetTracesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsGetTracesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsGetTracesResponse) ProtoMessage() {}

func (x *StatisticsGetTracesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsGetTracesResponse.ProtoReflect.Descriptor instead.
func (*StatisticsGetTracesResponse) Descriptor() ([]byte, []int) {
	return file_statistics_messages_proto_rawDescGZIP(), []int{3}
}

func (x *StatisticsGetTracesResponse) GetTraces() []*Trace {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *StatisticsGetTracesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StatisticsGetTracesResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type StatsEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int32    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Value    float32  `protobuf:"fixed32,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Datetime int64    `protobuf:"varint,3,opt,name=Datetime,proto3" json:"Datetime,omitempty"`
	Dataset  *Dataset `protobuf:"bytes,4,opt,name=Dataset,proto3" json:"Dataset,omitempty"`
}

func (x *StatsEvent) Reset() {
	*x = StatsEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsEvent) ProtoMessage() {}

func (x *StatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsEvent.ProtoReflect.Descriptor instead.
func (*StatsEvent) Descriptor() ([]byte, []int) {
	return file_statistics_messages_proto_rawDescGZIP(), []int{4}
}

func (x *StatsEvent) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StatsEvent) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StatsEvent) GetDatetime() int64 {
	if x != nil {
		return x.Datetime
	}
	return 0
}

func (x *StatsEvent) GetDataset() *Dataset {
	if x != nil {
		return x.Dataset
	}
	return nil
}

type Dataset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label           string `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	BackgroundColor string `protobuf:"bytes,2,opt,name=BackgroundColor,proto3" json:"BackgroundColor,omitempty"`
	BorderColor     string `protobuf:"bytes,3,opt,name=BorderColor,proto3" json:"BorderColor,omitempty"`
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_statistics_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_statistics_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Dataset) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Dataset) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *Dataset) GetBorderColor() string {
	if x != nil {
		return x.BorderColor
	}
	return ""
}

var File_statistics_messages_proto protoreflect.FileDescriptor

var file_statistics_messages_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x1a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a,
	0x17, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x6c, 0x6f, 0x77,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x6c, 0x6f, 0x77, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x22, 0x43,
	0x0a, 0x18, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x74, 0x0a, 0x1a, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x6c, 0x6f, 0x77, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x46, 0x6c, 0x6f, 0x77, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x45, 0x6e,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x6f, 0x0a, 0x1b, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x52, 0x06, 0x54, 0x72, 0x61, 0x63, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x7c, 0x0a, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x52,
	0x07, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x22, 0x6b, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x42, 0x61, 0x63,
	0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x67,
	0x6f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_statistics_messages_proto_rawDescOnce sync.Once
	file_statistics_messages_proto_rawDescData = file_statistics_messages_proto_rawDesc
)

func file_statistics_messages_proto_rawDescGZIP() []byte {
	file_statistics_messages_proto_rawDescOnce.Do(func() {
		file_statistics_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_statistics_messages_proto_rawDescData)
	})
	return file_statistics_messages_proto_rawDescData
}

var file_statistics_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_statistics_messages_proto_goTypes = []interface{}{
	(*StatisticsStreamRequest)(nil),     // 0: api.StatisticsStreamRequest
	(*StatisticsStreamResponse)(nil),    // 1: api.StatisticsStreamResponse
	(*StatisticsGetTracesRequest)(nil),  // 2: api.StatisticsGetTracesRequest
	(*StatisticsGetTracesResponse)(nil), // 3: api.StatisticsGetTracesResponse
	(*StatsEvent)(nil),                  // 4: api.StatsEvent
	(*Dataset)(nil),                     // 5: api.Dataset
	(*Trace)(nil),                       // 6: api.Trace
}
var file_statistics_messages_proto_depIdxs = []int32{
	4, // 0: api.StatisticsStreamResponse.Events:type_name -> api.StatsEvent
	6, // 1: api.StatisticsGetTracesResponse.Traces:type_name -> api.Trace
	5, // 2: api.StatsEvent.Dataset:type_name -> api.Dataset
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_statistics_messages_proto_init() }
func file_statistics_messages_proto_init() {
	if File_statistics_messages_proto != nil {
		return
	}
	file_trace_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_statistics_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsGetTracesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsGetTracesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_statistics_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dataset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_statistics_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_statistics_messages_proto_goTypes,
		DependencyIndexes: file_statistics_messages_proto_depIdxs,
		MessageInfos:      file_statistics_messages_proto_msgTypes,
	}.Build()
	File_statistics_messages_proto = out.File
	file_statistics_messages_proto_rawDesc = nil
	file_statistics_messages_proto_goTypes = nil
	file_statistics_messages_proto_depIdxs = nil
}
