// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	GetStream(ctx context.Context, in *StatisticsStreamRequest, opts ...grpc.CallOption) (StatisticsService_GetStreamClient, error)
	GetTraces(ctx context.Context, in *StatisticsGetTracesRequest, opts ...grpc.CallOption) (*StatisticsGetTracesResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetStream(ctx context.Context, in *StatisticsStreamRequest, opts ...grpc.CallOption) (StatisticsService_GetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StatisticsService_ServiceDesc.Streams[0], "/api.StatisticsService/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &statisticsServiceGetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StatisticsService_GetStreamClient interface {
	Recv() (*StatisticsStreamResponse, error)
	grpc.ClientStream
}

type statisticsServiceGetStreamClient struct {
	grpc.ClientStream
}

func (x *statisticsServiceGetStreamClient) Recv() (*StatisticsStreamResponse, error) {
	m := new(StatisticsStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *statisticsServiceClient) GetTraces(ctx context.Context, in *StatisticsGetTracesRequest, opts ...grpc.CallOption) (*StatisticsGetTracesResponse, error) {
	out := new(StatisticsGetTracesResponse)
	err := c.cc.Invoke(ctx, "/api.StatisticsService/GetTraces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility
type StatisticsServiceServer interface {
	GetStream(*StatisticsStreamRequest, StatisticsService_GetStreamServer) error
	GetTraces(context.Context, *StatisticsGetTracesRequest) (*StatisticsGetTracesResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticsServiceServer struct {
}

func (UnimplementedStatisticsServiceServer) GetStream(*StatisticsStreamRequest, StatisticsService_GetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedStatisticsServiceServer) GetTraces(context.Context, *StatisticsGetTracesRequest) (*StatisticsGetTracesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTraces not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatisticsStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatisticsServiceServer).GetStream(m, &statisticsServiceGetStreamServer{stream})
}

type StatisticsService_GetStreamServer interface {
	Send(*StatisticsStreamResponse) error
	grpc.ServerStream
}

type statisticsServiceGetStreamServer struct {
	grpc.ServerStream
}

func (x *statisticsServiceGetStreamServer) Send(m *StatisticsStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StatisticsService_GetTraces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsGetTracesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetTraces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StatisticsService/GetTraces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetTraces(ctx, req.(*StatisticsGetTracesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTraces",
			Handler:    _StatisticsService_GetTraces_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _StatisticsService_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "statistics.service.proto",
}
