// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: stats.messages.proto

package api

import (
	v1 "go.opentelemetry.io/proto/otlp/trace/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowID        string                 `protobuf:"bytes,1,opt,name=FlowID,proto3" json:"FlowID,omitempty"`
	ProjectID     string                 `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	Metrics       []string               `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsStreamRequest) Reset() {
	*x = StatisticsStreamRequest{}
	mi := &file_stats_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsStreamRequest) ProtoMessage() {}

func (x *StatisticsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsStreamRequest.ProtoReflect.Descriptor instead.
func (*StatisticsStreamRequest) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{0}
}

func (x *StatisticsStreamRequest) GetFlowID() string {
	if x != nil {
		return x.FlowID
	}
	return ""
}

func (x *StatisticsStreamRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *StatisticsStreamRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type StatisticsStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*StatsEvent          `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsStreamResponse) Reset() {
	*x = StatisticsStreamResponse{}
	mi := &file_stats_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsStreamResponse) ProtoMessage() {}

func (x *StatisticsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsStreamResponse.ProtoReflect.Descriptor instead.
func (*StatisticsStreamResponse) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{1}
}

func (x *StatisticsStreamResponse) GetEvents() []*StatsEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type StatisticsGetTracesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowID        string                 `protobuf:"bytes,1,opt,name=FlowID,proto3" json:"FlowID,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=End,proto3" json:"End,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
	ProjectID     string                 `protobuf:"bytes,5,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsGetTracesRequest) Reset() {
	*x = StatisticsGetTracesRequest{}
	mi := &file_stats_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsGetTracesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsGetTracesRequest) ProtoMessage() {}

func (x *StatisticsGetTracesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsGetTracesRequest.ProtoReflect.Descriptor instead.
func (*StatisticsGetTracesRequest) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{2}
}

func (x *StatisticsGetTracesRequest) GetFlowID() string {
	if x != nil {
		return x.FlowID
	}
	return ""
}

func (x *StatisticsGetTracesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *StatisticsGetTracesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *StatisticsGetTracesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StatisticsGetTracesRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

type StatisticsGetTracesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*TraceInfo           `protobuf:"bytes,1,rep,name=Traces,proto3" json:"Traces,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticsGetTracesResponse) Reset() {
	*x = StatisticsGetTracesResponse{}
	mi := &file_stats_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticsGetTracesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsGetTracesResponse) ProtoMessage() {}

func (x *StatisticsGetTracesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsGetTracesResponse.ProtoReflect.Descriptor instead.
func (*StatisticsGetTracesResponse) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{3}
}

func (x *StatisticsGetTracesResponse) GetTraces() []*TraceInfo {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *StatisticsGetTracesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StatisticsGetTracesResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type StatsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=Metric,proto3" json:"Metric,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Datetime      int64                  `protobuf:"varint,3,opt,name=Datetime,proto3" json:"Datetime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsEvent) Reset() {
	*x = StatsEvent{}
	mi := &file_stats_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsEvent) ProtoMessage() {}

func (x *StatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsEvent.ProtoReflect.Descriptor instead.
func (*StatsEvent) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{4}
}

func (x *StatsEvent) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *StatsEvent) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StatsEvent) GetDatetime() int64 {
	if x != nil {
		return x.Datetime
	}
	return 0
}

type Dataset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Label           string                 `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	BackgroundColor string                 `protobuf:"bytes,2,opt,name=BackgroundColor,proto3" json:"BackgroundColor,omitempty"`
	BorderColor     string                 `protobuf:"bytes,3,opt,name=BorderColor,proto3" json:"BorderColor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	mi := &file_stats_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Dataset) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Dataset) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *Dataset) GetBorderColor() string {
	if x != nil {
		return x.BorderColor
	}
	return ""
}

// QueryMetricRequest requests data for a specific metric
type QueryMetricRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Project identifier
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Optional: Flow identifier. If empty, aggregates across all flows
	FlowId string `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	// Required: Metric names (e.g., "tiny_span_error_count", "tiny_trace_count")
	Metrics []string `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// Required: Start of time range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Required: End of time range
	EndTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Optional: Downsample configuration
	Downsample    *DownsampleConfig    `protobuf:"bytes,6,opt,name=downsample,proto3" json:"downsample,omitempty"`
	BucketSize    *durationpb.Duration `protobuf:"bytes,7,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricRequest) Reset() {
	*x = QueryMetricRequest{}
	mi := &file_stats_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricRequest) ProtoMessage() {}

func (x *QueryMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricRequest.ProtoReflect.Descriptor instead.
func (*QueryMetricRequest) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{6}
}

func (x *QueryMetricRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *QueryMetricRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *QueryMetricRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *QueryMetricRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryMetricRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryMetricRequest) GetDownsample() *DownsampleConfig {
	if x != nil {
		return x.Downsample
	}
	return nil
}

func (x *QueryMetricRequest) GetBucketSize() *durationpb.Duration {
	if x != nil {
		return x.BucketSize
	}
	return nil
}

// DownsampleConfig controls server-side downsampling
type DownsampleConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, enable downsampling
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Number of data points to return (e.g., 100 for charts)
	// If 0 or not set, returns all points
	MaxPoints     int32 `protobuf:"varint,2,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownsampleConfig) Reset() {
	*x = DownsampleConfig{}
	mi := &file_stats_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownsampleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownsampleConfig) ProtoMessage() {}

func (x *DownsampleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownsampleConfig.ProtoReflect.Descriptor instead.
func (*DownsampleConfig) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DownsampleConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DownsampleConfig) GetMaxPoints() int32 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

// QueryMetricResponse contains the query result
type QueryMetricResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metric information
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FlowId    string `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"` // Empty if aggregated across flows
	// Time range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Metrics   map[string]*MetricData `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Metadata
	Downsampled        bool  `protobuf:"varint,6,opt,name=downsampled,proto3" json:"downsampled,omitempty"`                                           // True if downsampling was applied
	OriginalPointCount int32 `protobuf:"varint,7,opt,name=original_point_count,json=originalPointCount,proto3" json:"original_point_count,omitempty"` // Original count before downsampling
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueryMetricResponse) Reset() {
	*x = QueryMetricResponse{}
	mi := &file_stats_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricResponse) ProtoMessage() {}

func (x *QueryMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricResponse.ProtoReflect.Descriptor instead.
func (*QueryMetricResponse) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{8}
}

func (x *QueryMetricResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *QueryMetricResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *QueryMetricResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryMetricResponse) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryMetricResponse) GetMetrics() map[string]*MetricData {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *QueryMetricResponse) GetDownsampled() bool {
	if x != nil {
		return x.Downsampled
	}
	return false
}

func (x *QueryMetricResponse) GetOriginalPointCount() int32 {
	if x != nil {
		return x.OriginalPointCount
	}
	return 0
}

// Metric data structure
type MetricData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Metric             string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Stats              *MetricStatistics      `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Points             []*DataPoint           `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	OriginalPointCount int32                  `protobuf:"varint,4,opt,name=original_point_count,json=originalPointCount,proto3" json:"original_point_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricData) Reset() {
	*x = MetricData{}
	mi := &file_stats_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricData) ProtoMessage() {}

func (x *MetricData) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricData.ProtoReflect.Descriptor instead.
func (*MetricData) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{9}
}

func (x *MetricData) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricData) GetStats() *MetricStatistics {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *MetricData) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *MetricData) GetOriginalPointCount() int32 {
	if x != nil {
		return x.OriginalPointCount
	}
	return 0
}

// MetricStatistics contains aggregated statistics
type MetricStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           float64                `protobuf:"fixed64,1,opt,name=sum,proto3" json:"sum,omitempty"`    // Total sum over time range
	Avg           float64                `protobuf:"fixed64,2,opt,name=avg,proto3" json:"avg,omitempty"`    // Average value
	Min           float64                `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`    // Minimum value
	Max           float64                `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`    // Maximum value
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"` // Number of data points
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricStatistics) Reset() {
	*x = MetricStatistics{}
	mi := &file_stats_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricStatistics) ProtoMessage() {}

func (x *MetricStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricStatistics.ProtoReflect.Descriptor instead.
func (*MetricStatistics) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{10}
}

func (x *MetricStatistics) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *MetricStatistics) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *MetricStatistics) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *MetricStatistics) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *MetricStatistics) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// DataPoint represents a single metric observation
type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_stats_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{11}
}

func (x *DataPoint) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DataPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// GetProjectSummaryRequest requests summary for a project
type GetProjectSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Project identifier
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Optional: Flow identifier. If empty, aggregates across all flows
	FlowId string `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	// Required: Start of time range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Required: End of time range
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectSummaryRequest) Reset() {
	*x = GetProjectSummaryRequest{}
	mi := &file_stats_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectSummaryRequest) ProtoMessage() {}

func (x *GetProjectSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetProjectSummaryRequest) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{12}
}

func (x *GetProjectSummaryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetProjectSummaryRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *GetProjectSummaryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetProjectSummaryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// GetProjectSummaryResponse contains project summary
type GetProjectSummaryResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FlowId    string                 `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"` // Empty if all flows
	// Time range
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Metrics summary (key = metric name)
	Metrics       map[string]*MetricSummary `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectSummaryResponse) Reset() {
	*x = GetProjectSummaryResponse{}
	mi := &file_stats_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectSummaryResponse) ProtoMessage() {}

func (x *GetProjectSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetProjectSummaryResponse) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GetProjectSummaryResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetProjectSummaryResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *GetProjectSummaryResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetProjectSummaryResponse) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetProjectSummaryResponse) GetMetrics() map[string]*MetricSummary {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// MetricSummary contains summary for a single metric
type MetricSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sum           float64                `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`
	Avg           float64                `protobuf:"fixed64,3,opt,name=avg,proto3" json:"avg,omitempty"`
	Min           float64                `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,5,opt,name=max,proto3" json:"max,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Latest        float64                `protobuf:"fixed64,7,opt,name=latest,proto3" json:"latest,omitempty"` // Most recent value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSummary) Reset() {
	*x = MetricSummary{}
	mi := &file_stats_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSummary) ProtoMessage() {}

func (x *MetricSummary) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSummary.ProtoReflect.Descriptor instead.
func (*MetricSummary) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{14}
}

func (x *MetricSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSummary) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *MetricSummary) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *MetricSummary) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *MetricSummary) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *MetricSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MetricSummary) GetLatest() float64 {
	if x != nil {
		return x.Latest
	}
	return 0
}

// GetAvailableFlowsRequest requests list of flows
type GetAvailableFlowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Project identifier
	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableFlowsRequest) Reset() {
	*x = GetAvailableFlowsRequest{}
	mi := &file_stats_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableFlowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableFlowsRequest) ProtoMessage() {}

func (x *GetAvailableFlowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableFlowsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableFlowsRequest) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{15}
}

func (x *GetAvailableFlowsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// GetAvailableFlowsResponse returns list of flows
type GetAvailableFlowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FlowIds       []string               `protobuf:"bytes,2,rep,name=flow_ids,json=flowIds,proto3" json:"flow_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableFlowsResponse) Reset() {
	*x = GetAvailableFlowsResponse{}
	mi := &file_stats_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableFlowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableFlowsResponse) ProtoMessage() {}

func (x *GetAvailableFlowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableFlowsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableFlowsResponse) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{16}
}

func (x *GetAvailableFlowsResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetAvailableFlowsResponse) GetFlowIds() []string {
	if x != nil {
		return x.FlowIds
	}
	return nil
}

// GetAvailableMetricsRequest requests list of available metrics
type GetAvailableMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Project identifier
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Optional: Flow identifier. If empty, returns metrics across all flows
	FlowId        string `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableMetricsRequest) Reset() {
	*x = GetAvailableMetricsRequest{}
	mi := &file_stats_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableMetricsRequest) ProtoMessage() {}

func (x *GetAvailableMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableMetricsRequest) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{17}
}

func (x *GetAvailableMetricsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetAvailableMetricsRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

// GetAvailableMetricsResponse returns list of metrics
type GetAvailableMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FlowId        string                 `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"` // Empty if all flows
	Metrics       []string               `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableMetricsResponse) Reset() {
	*x = GetAvailableMetricsResponse{}
	mi := &file_stats_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableMetricsResponse) ProtoMessage() {}

func (x *GetAvailableMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableMetricsResponse) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{18}
}

func (x *GetAvailableMetricsResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetAvailableMetricsResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *GetAvailableMetricsResponse) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GetTraceByIDRequest requests a full trace by its ID
type GetTraceByIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required: Trace ID
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Required: Project ID for authorization
	ProjectId     string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceByIDRequest) Reset() {
	*x = GetTraceByIDRequest{}
	mi := &file_stats_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceByIDRequest) ProtoMessage() {}

func (x *GetTraceByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTraceByIDRequest) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{19}
}

func (x *GetTraceByIDRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetTraceByIDRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// GetTraceByIDResponse returns complete trace information with all spans
type GetTraceByIDResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TraceId     string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ProjectId   string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	FlowId      string                 `protobuf:"bytes,3,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	StartTime   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SpansCount  int32                  `protobuf:"varint,6,opt,name=spans_count,json=spansCount,proto3" json:"spans_count,omitempty"`
	ErrorsCount int32                  `protobuf:"varint,7,opt,name=errors_count,json=errorsCount,proto3" json:"errors_count,omitempty"`
	DataCount   int32                  `protobuf:"varint,8,opt,name=data_count,json=dataCount,proto3" json:"data_count,omitempty"`
	DataLength  int64                  `protobuf:"varint,9,opt,name=data_length,json=dataLength,proto3" json:"data_length,omitempty"`
	DurationNs  uint64                 `protobuf:"varint,10,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	// Using OpenTelemetry's Span definition
	Spans         []*v1.Span `protobuf:"bytes,11,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceByIDResponse) Reset() {
	*x = GetTraceByIDResponse{}
	mi := &file_stats_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceByIDResponse) ProtoMessage() {}

func (x *GetTraceByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTraceByIDResponse) Descriptor() ([]byte, []int) {
	return file_stats_messages_proto_rawDescGZIP(), []int{20}
}

func (x *GetTraceByIDResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetTraceByIDResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetTraceByIDResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *GetTraceByIDResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetTraceByIDResponse) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetTraceByIDResponse) GetSpansCount() int32 {
	if x != nil {
		return x.SpansCount
	}
	return 0
}

func (x *GetTraceByIDResponse) GetErrorsCount() int32 {
	if x != nil {
		return x.ErrorsCount
	}
	return 0
}

func (x *GetTraceByIDResponse) GetDataCount() int32 {
	if x != nil {
		return x.DataCount
	}
	return 0
}

func (x *GetTraceByIDResponse) GetDataLength() int64 {
	if x != nil {
		return x.DataLength
	}
	return 0
}

func (x *GetTraceByIDResponse) GetDurationNs() uint64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *GetTraceByIDResponse) GetSpans() []*v1.Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

var File_stats_messages_proto protoreflect.FileDescriptor

const file_stats_messages_proto_rawDesc = "" +
	"\n" +
	"\x14stats.messages.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\vtrace.proto\x1a(opentelemetry/proto/trace/v1/trace.proto\"i\n" +
	"\x17StatisticsStreamRequest\x12\x16\n" +
	"\x06FlowID\x18\x01 \x01(\tR\x06FlowID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12\x18\n" +
	"\ametrics\x18\x03 \x03(\tR\ametrics\"C\n" +
	"\x18StatisticsStreamResponse\x12'\n" +
	"\x06Events\x18\x01 \x03(\v2\x0f.api.StatsEventR\x06Events\"\xca\x01\n" +
	"\x1aStatisticsGetTracesRequest\x12\x16\n" +
	"\x06FlowID\x18\x01 \x01(\tR\x06FlowID\x120\n" +
	"\x05Start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05Start\x12,\n" +
	"\x03End\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03End\x12\x16\n" +
	"\x06Offset\x18\x04 \x01(\x03R\x06Offset\x12\x1c\n" +
	"\tProjectID\x18\x05 \x01(\tR\tProjectID\"s\n" +
	"\x1bStatisticsGetTracesResponse\x12&\n" +
	"\x06Traces\x18\x01 \x03(\v2\x0e.api.TraceInfoR\x06Traces\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x03R\x05Total\x12\x16\n" +
	"\x06Offset\x18\x03 \x01(\x03R\x06Offset\"V\n" +
	"\n" +
	"StatsEvent\x12\x16\n" +
	"\x06Metric\x18\x01 \x01(\tR\x06Metric\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x01R\x05Value\x12\x1a\n" +
	"\bDatetime\x18\x03 \x01(\x03R\bDatetime\"k\n" +
	"\aDataset\x12\x14\n" +
	"\x05Label\x18\x01 \x01(\tR\x05Label\x12(\n" +
	"\x0fBackgroundColor\x18\x02 \x01(\tR\x0fBackgroundColor\x12 \n" +
	"\vBorderColor\x18\x03 \x01(\tR\vBorderColor\"\xcb\x02\n" +
	"\x12QueryMetricRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x12\x18\n" +
	"\ametrics\x18\x03 \x03(\tR\ametrics\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x125\n" +
	"\n" +
	"downsample\x18\x06 \x01(\v2\x15.api.DownsampleConfigR\n" +
	"downsample\x12:\n" +
	"\vbucket_size\x18\a \x01(\v2\x19.google.protobuf.DurationR\n" +
	"bucketSize\"K\n" +
	"\x10DownsampleConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"max_points\x18\x02 \x01(\x05R\tmaxPoints\"\xa1\x03\n" +
	"\x13QueryMetricResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12?\n" +
	"\ametrics\x18\x05 \x03(\v2%.api.QueryMetricResponse.MetricsEntryR\ametrics\x12 \n" +
	"\vdownsampled\x18\x06 \x01(\bR\vdownsampled\x120\n" +
	"\x14original_point_count\x18\a \x01(\x05R\x12originalPointCount\x1aK\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.api.MetricDataR\x05value:\x028\x01\"\xab\x01\n" +
	"\n" +
	"MetricData\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12+\n" +
	"\x05stats\x18\x02 \x01(\v2\x15.api.MetricStatisticsR\x05stats\x12&\n" +
	"\x06points\x18\x03 \x03(\v2\x0e.api.DataPointR\x06points\x120\n" +
	"\x14original_point_count\x18\x04 \x01(\x05R\x12originalPointCount\"p\n" +
	"\x10MetricStatistics\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x01R\x03sum\x12\x10\n" +
	"\x03avg\x18\x02 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x01R\x03max\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"\xc0\x01\n" +
	"\tDataPoint\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x122\n" +
	"\x06labels\x18\x03 \x03(\v2\x1a.api.DataPoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x01\n" +
	"\x18GetProjectSummaryRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xdc\x02\n" +
	"\x19GetProjectSummaryResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12E\n" +
	"\ametrics\x18\x05 \x03(\v2+.api.GetProjectSummaryResponse.MetricsEntryR\ametrics\x1aN\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.api.MetricSummaryR\x05value:\x028\x01\"\x99\x01\n" +
	"\rMetricSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x01R\x03sum\x12\x10\n" +
	"\x03avg\x18\x03 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x01R\x03max\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x12\x16\n" +
	"\x06latest\x18\a \x01(\x01R\x06latest\"9\n" +
	"\x18GetAvailableFlowsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"U\n" +
	"\x19GetAvailableFlowsResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\bflow_ids\x18\x02 \x03(\tR\aflowIds\"T\n" +
	"\x1aGetAvailableMetricsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\"o\n" +
	"\x1bGetAvailableMetricsResponse\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x12\x18\n" +
	"\ametrics\x18\x03 \x03(\tR\ametrics\"O\n" +
	"\x13GetTraceByIDRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\xba\x03\n" +
	"\x14GetTraceByIDResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\aflow_id\x18\x03 \x01(\tR\x06flowId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vspans_count\x18\x06 \x01(\x05R\n" +
	"spansCount\x12!\n" +
	"\ferrors_count\x18\a \x01(\x05R\verrorsCount\x12\x1d\n" +
	"\n" +
	"data_count\x18\b \x01(\x05R\tdataCount\x12\x1f\n" +
	"\vdata_length\x18\t \x01(\x03R\n" +
	"dataLength\x12\x1f\n" +
	"\vduration_ns\x18\n" +
	" \x01(\x04R\n" +
	"durationNs\x128\n" +
	"\x05spans\x18\v \x03(\v2\".opentelemetry.proto.trace.v1.SpanR\x05spansB\x0eZ\f./api-go;apib\x06proto3"

var (
	file_stats_messages_proto_rawDescOnce sync.Once
	file_stats_messages_proto_rawDescData []byte
)

func file_stats_messages_proto_rawDescGZIP() []byte {
	file_stats_messages_proto_rawDescOnce.Do(func() {
		file_stats_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_messages_proto_rawDesc), len(file_stats_messages_proto_rawDesc)))
	})
	return file_stats_messages_proto_rawDescData
}

var file_stats_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_stats_messages_proto_goTypes = []any{
	(*StatisticsStreamRequest)(nil),     // 0: api.StatisticsStreamRequest
	(*StatisticsStreamResponse)(nil),    // 1: api.StatisticsStreamResponse
	(*StatisticsGetTracesRequest)(nil),  // 2: api.StatisticsGetTracesRequest
	(*StatisticsGetTracesResponse)(nil), // 3: api.StatisticsGetTracesResponse
	(*StatsEvent)(nil),                  // 4: api.StatsEvent
	(*Dataset)(nil),                     // 5: api.Dataset
	(*QueryMetricRequest)(nil),          // 6: api.QueryMetricRequest
	(*DownsampleConfig)(nil),            // 7: api.DownsampleConfig
	(*QueryMetricResponse)(nil),         // 8: api.QueryMetricResponse
	(*MetricData)(nil),                  // 9: api.MetricData
	(*MetricStatistics)(nil),            // 10: api.MetricStatistics
	(*DataPoint)(nil),                   // 11: api.DataPoint
	(*GetProjectSummaryRequest)(nil),    // 12: api.GetProjectSummaryRequest
	(*GetProjectSummaryResponse)(nil),   // 13: api.GetProjectSummaryResponse
	(*MetricSummary)(nil),               // 14: api.MetricSummary
	(*GetAvailableFlowsRequest)(nil),    // 15: api.GetAvailableFlowsRequest
	(*GetAvailableFlowsResponse)(nil),   // 16: api.GetAvailableFlowsResponse
	(*GetAvailableMetricsRequest)(nil),  // 17: api.GetAvailableMetricsRequest
	(*GetAvailableMetricsResponse)(nil), // 18: api.GetAvailableMetricsResponse
	(*GetTraceByIDRequest)(nil),         // 19: api.GetTraceByIDRequest
	(*GetTraceByIDResponse)(nil),        // 20: api.GetTraceByIDResponse
	nil,                                 // 21: api.QueryMetricResponse.MetricsEntry
	nil,                                 // 22: api.DataPoint.LabelsEntry
	nil,                                 // 23: api.GetProjectSummaryResponse.MetricsEntry
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
	(*TraceInfo)(nil),                   // 25: api.TraceInfo
	(*durationpb.Duration)(nil),         // 26: google.protobuf.Duration
	(*v1.Span)(nil),                     // 27: opentelemetry.proto.trace.v1.Span
}
var file_stats_messages_proto_depIdxs = []int32{
	4,  // 0: api.StatisticsStreamResponse.Events:type_name -> api.StatsEvent
	24, // 1: api.StatisticsGetTracesRequest.Start:type_name -> google.protobuf.Timestamp
	24, // 2: api.StatisticsGetTracesRequest.End:type_name -> google.protobuf.Timestamp
	25, // 3: api.StatisticsGetTracesResponse.Traces:type_name -> api.TraceInfo
	24, // 4: api.QueryMetricRequest.start_time:type_name -> google.protobuf.Timestamp
	24, // 5: api.QueryMetricRequest.end_time:type_name -> google.protobuf.Timestamp
	7,  // 6: api.QueryMetricRequest.downsample:type_name -> api.DownsampleConfig
	26, // 7: api.QueryMetricRequest.bucket_size:type_name -> google.protobuf.Duration
	24, // 8: api.QueryMetricResponse.start_time:type_name -> google.protobuf.Timestamp
	24, // 9: api.QueryMetricResponse.end_time:type_name -> google.protobuf.Timestamp
	21, // 10: api.QueryMetricResponse.metrics:type_name -> api.QueryMetricResponse.MetricsEntry
	10, // 11: api.MetricData.stats:type_name -> api.MetricStatistics
	11, // 12: api.MetricData.points:type_name -> api.DataPoint
	24, // 13: api.DataPoint.time:type_name -> google.protobuf.Timestamp
	22, // 14: api.DataPoint.labels:type_name -> api.DataPoint.LabelsEntry
	24, // 15: api.GetProjectSummaryRequest.start_time:type_name -> google.protobuf.Timestamp
	24, // 16: api.GetProjectSummaryRequest.end_time:type_name -> google.protobuf.Timestamp
	24, // 17: api.GetProjectSummaryResponse.start_time:type_name -> google.protobuf.Timestamp
	24, // 18: api.GetProjectSummaryResponse.end_time:type_name -> google.protobuf.Timestamp
	23, // 19: api.GetProjectSummaryResponse.metrics:type_name -> api.GetProjectSummaryResponse.MetricsEntry
	24, // 20: api.GetTraceByIDResponse.start_time:type_name -> google.protobuf.Timestamp
	24, // 21: api.GetTraceByIDResponse.end_time:type_name -> google.protobuf.Timestamp
	27, // 22: api.GetTraceByIDResponse.spans:type_name -> opentelemetry.proto.trace.v1.Span
	9,  // 23: api.QueryMetricResponse.MetricsEntry.value:type_name -> api.MetricData
	14, // 24: api.GetProjectSummaryResponse.MetricsEntry.value:type_name -> api.MetricSummary
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_stats_messages_proto_init() }
func file_stats_messages_proto_init() {
	if File_stats_messages_proto != nil {
		return
	}
	file_trace_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_messages_proto_rawDesc), len(file_stats_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stats_messages_proto_goTypes,
		DependencyIndexes: file_stats_messages_proto_depIdxs,
		MessageInfos:      file_stats_messages_proto_msgTypes,
	}.Build()
	File_stats_messages_proto = out.File
	file_stats_messages_proto_goTypes = nil
	file_stats_messages_proto_depIdxs = nil
}
