// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: stats.service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_stats_service_proto protoreflect.FileDescriptor

const file_stats_service_proto_rawDesc = "" +
	"\n" +
	"\x13stats.service.proto\x12\x03api\x1a\x14stats.messages.proto2\xb8\x04\n" +
	"\x11StatisticsService\x12J\n" +
	"\tGetStream\x12\x1c.api.StatisticsStreamRequest\x1a\x1d.api.StatisticsStreamResponse0\x01\x12N\n" +
	"\tGetTraces\x12\x1f.api.StatisticsGetTracesRequest\x1a .api.StatisticsGetTracesResponse\x12@\n" +
	"\vQueryMetric\x12\x17.api.QueryMetricRequest\x1a\x18.api.QueryMetricResponse\x12R\n" +
	"\x11GetProjectSummary\x12\x1d.api.GetProjectSummaryRequest\x1a\x1e.api.GetProjectSummaryResponse\x12R\n" +
	"\x11GetAvailableFlows\x12\x1d.api.GetAvailableFlowsRequest\x1a\x1e.api.GetAvailableFlowsResponse\x12X\n" +
	"\x13GetAvailableMetrics\x12\x1f.api.GetAvailableMetricsRequest\x1a .api.GetAvailableMetricsResponse\x12C\n" +
	"\fGetTraceByID\x12\x18.api.GetTraceByIDRequest\x1a\x19.api.GetTraceByIDResponseB\x0eZ\f./api-go;apib\x06proto3"

var file_stats_service_proto_goTypes = []any{
	(*StatisticsStreamRequest)(nil),     // 0: api.StatisticsStreamRequest
	(*StatisticsGetTracesRequest)(nil),  // 1: api.StatisticsGetTracesRequest
	(*QueryMetricRequest)(nil),          // 2: api.QueryMetricRequest
	(*GetProjectSummaryRequest)(nil),    // 3: api.GetProjectSummaryRequest
	(*GetAvailableFlowsRequest)(nil),    // 4: api.GetAvailableFlowsRequest
	(*GetAvailableMetricsRequest)(nil),  // 5: api.GetAvailableMetricsRequest
	(*GetTraceByIDRequest)(nil),         // 6: api.GetTraceByIDRequest
	(*StatisticsStreamResponse)(nil),    // 7: api.StatisticsStreamResponse
	(*StatisticsGetTracesResponse)(nil), // 8: api.StatisticsGetTracesResponse
	(*QueryMetricResponse)(nil),         // 9: api.QueryMetricResponse
	(*GetProjectSummaryResponse)(nil),   // 10: api.GetProjectSummaryResponse
	(*GetAvailableFlowsResponse)(nil),   // 11: api.GetAvailableFlowsResponse
	(*GetAvailableMetricsResponse)(nil), // 12: api.GetAvailableMetricsResponse
	(*GetTraceByIDResponse)(nil),        // 13: api.GetTraceByIDResponse
}
var file_stats_service_proto_depIdxs = []int32{
	0,  // 0: api.StatisticsService.GetStream:input_type -> api.StatisticsStreamRequest
	1,  // 1: api.StatisticsService.GetTraces:input_type -> api.StatisticsGetTracesRequest
	2,  // 2: api.StatisticsService.QueryMetric:input_type -> api.QueryMetricRequest
	3,  // 3: api.StatisticsService.GetProjectSummary:input_type -> api.GetProjectSummaryRequest
	4,  // 4: api.StatisticsService.GetAvailableFlows:input_type -> api.GetAvailableFlowsRequest
	5,  // 5: api.StatisticsService.GetAvailableMetrics:input_type -> api.GetAvailableMetricsRequest
	6,  // 6: api.StatisticsService.GetTraceByID:input_type -> api.GetTraceByIDRequest
	7,  // 7: api.StatisticsService.GetStream:output_type -> api.StatisticsStreamResponse
	8,  // 8: api.StatisticsService.GetTraces:output_type -> api.StatisticsGetTracesResponse
	9,  // 9: api.StatisticsService.QueryMetric:output_type -> api.QueryMetricResponse
	10, // 10: api.StatisticsService.GetProjectSummary:output_type -> api.GetProjectSummaryResponse
	11, // 11: api.StatisticsService.GetAvailableFlows:output_type -> api.GetAvailableFlowsResponse
	12, // 12: api.StatisticsService.GetAvailableMetrics:output_type -> api.GetAvailableMetricsResponse
	13, // 13: api.StatisticsService.GetTraceByID:output_type -> api.GetTraceByIDResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_stats_service_proto_init() }
func file_stats_service_proto_init() {
	if File_stats_service_proto != nil {
		return
	}
	file_stats_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_service_proto_rawDesc), len(file_stats_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_service_proto_goTypes,
		DependencyIndexes: file_stats_service_proto_depIdxs,
	}.Build()
	File_stats_service_proto = out.File
	file_stats_service_proto_goTypes = nil
	file_stats_service_proto_depIdxs = nil
}
